name: ai_education
description: "AI Education Mobile App (16 KB Page Aligned Flutter)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  shared_preferences: ^2.3.3
  google_fonts: ^6.2.1
  intl: ^0.19.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#090B0E"
  adaptive_icon_foreground: "assets/app_icon_foreground.png"

flutter_native_splash:
  color: "#090B0E"
  image: "assets/logo.png"
  android: true
  ios: false
  android_12:
    color: "#090B0E"
    image: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/app_icon.png
    - assets/app_icon_foreground.png
